# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PDF', 'PDF'), ('PAPERBACK', 'PAPERBACK'), ('AUDIO', 'AUDIO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(through='core.TypesProduct', to='core.ProductType'),
        ),
    ]
