# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161201_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudio',
            name='url',
            field=models.CharField(max_length=235),
        ),
        migrations.AlterField(
            model_name='productpaperback',
            name='url',
            field=models.CharField(max_length=235),
        ),
        migrations.AlterField(
            model_name='productpdf',
            name='url',
            field=models.CharField(max_length=235),
        ),
    ]
