# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
