# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161203_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('PDF', 'PDF'), ('PAPERBACK', 'PAPERBACK'), ('AUDIO', 'AUDIO')], max_length=10)),
                ('price', models.PositiveIntegerField(null=True)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Publication',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpaperback',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpdf',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductAudio',
        ),
        migrations.DeleteModel(
            name='ProductPaperback',
        ),
        migrations.DeleteModel(
            name='ProductPDF',
        ),
        migrations.AddField(
            model_name='publicationentity',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publication'),
        ),
    ]
