# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('card_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=40)),
                ('expiration_year', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
