# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
