# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 14:48
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=16, validators=[core.validators.validate_size]),
        ),
        migrations.AlterField(
            model_name='publicationentity',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
